### PR TITLE
Login Handler

### PR DESCRIPTION
**Pull request by baivabpokhrel**
Creating the UI such that login handling would be easier,
@Quetourah  and @ylin013  feel free to make changes according to the need.

### CODE REVIEW

**Comment by Quetourah** [comment]
There will be some conflicts with the changes I made. I will review the changes a bit later and see how I can avoid them. Don't merge yet.

**Comment by baivabpokhrel** [comment]
Yeah, I just wanted to have an overall picture of how it looks after login and how to redirect to profile page after login.

**Comment by Quetourah** [comment]
oh ok. Will make my updates soon. and we will be able to merge all of it and see what it looks like all together.  

how much of the profile were able to finish?

**Comment by baivabpokhrel** [comment]
@ylin013  is working on the profile and I was able to integrate editor into the website. Now I am figuring a way to send code from the editor.

**Pull request closed without merging**
