### PR TITLE
Revert "Create Song Dialogue Box Added"

### PR DESCRIPTION
**Pull request by Quetourah**
Reverts Quetourah/jamsession#34

### CODE REVIEW

**Comment by Quetourah** [comment]
There is an issue in the pull request I noticed when I tested your changes on my computer.

:exclamation: You removed the profile nav item, so now the user does not have an option to return to their profile page.

Also, you should add a save button for saving the changes to a song. We can implement it later, but I think you should add it now for design logic.

**Comment by Quetourah** [comment]
There is also a small spelling error. "Lets go live" should be "Let **'** s go live".

**Comment by baivabpokhrel** [comment]
I thought we could use the back button in the browser ti navigate back, but having a profile button makes it easily navigable, I will make those changes. 
I will look into the suggestions you made I will add those there in few minutes.

**Comment by Quetourah** [comment]
> I thought we could use the back button in the browser to navigate back, but having a profile button makes it easily navigable, I will make those changes.
> I will look into the suggestions you made I will nake changes in few minutes

ah. I see. uhm. I guess we don't have many pages now, but it might be a guessing game going back and forth like that, especially with saving changes. I think it's fine for going from the coding page to the profile page. but i think there should be a direct path from home to profile. we can discuss in more detail tomorrow so we're all on the same page, but I see what meant now.

**Pull request closed without merging**
